### ISSUE TITLE
stock NVIDIA benchmarks failing on a Xavier board

### ISSUE THREAD

**Issue by ens-lg4** [mlperf/inference_results_v0.5#23]
We were trying to reproduce NVIDIA's benchmarks using a Xavier board running JetPack 4.3,
without changing any configuration files.

First there was a minor (but a very annoying) issue when installing the dependencies using `closed/NVIDIA/scripts/install_xavier_dependencies.sh` script.  It ran into a circular dependency of pip packages (matplotlib==3.0.2 somehow picked up numpy==1.18.1 (a part of easy_install) which depended on Cython, which was missing at the moment of installing matplotlib). Workaround: install Cython before running the whole script.

Second problem is more cryptic. After installing the plugins, datasets, preprocessing, the command `make generate_engines` fails with the following:
```
[TensorRT] INFO: --------------- Layers running on DLA:
[TensorRT] INFO: {(Unnamed Layer* 0) [Convolution],(Unnamed Layer* 1) [Scale],(Unnamed Layer* 2) [Activation],(Unnamed Layer* 3) [Convolution],(Unnamed Layer* 4) [Scale],(Unnamed Layer* 5) [Activation],(Unnamed Layer* 6) [Convolution],(Unnamed Layer* 7) [Scale],(Unnamed Layer* 8) [Activation],(Unnamed Layer* 9) [Convolution],(Unnamed Layer* 10) [Scale],(Unnamed Layer* 11) [Activation],(Unnamed Layer* 12) [Convolution],(Unnamed Layer* 13) [Scale],(Unnamed Layer* 14) [Activation],(Unnamed Layer* 15) [Convolution],(Unnamed Layer* 16) [Scale],(Unnamed Layer* 17) [Activation],(Unnamed Layer* 18) [Convolution],(Unnamed Layer* 19) [Scale],(Unnamed Layer* 20) [Activation],(Unnamed Layer* 21) [Convolution],(Unnamed Layer* 22) [Scale],(Unnamed Layer* 23) [Activation],(Unnamed Layer* 24) [Convolution],(Unnamed Layer* 25) [Scale],(Unnamed Layer* 26) [Activation],(Unnamed Layer* 27) [Convolution],(Unnamed Layer* 28) [Scale],(Unnamed Layer* 29) [Activation],(Unnamed Layer* 30) [Convolution],(Unnamed Layer* 31) [Scale],(Unnamed Layer* 32) [Activation],(Unnamed Layer* 33) [Convolution],(Unnamed Layer* 34) [Scale],(Unnamed Layer* 35) [Activation],(Unnamed Layer* 36) [Convolution],(Unnamed Layer* 37) [Scale],(Unnamed Layer* 38) [Activation],(Unnamed Layer* 39) [Convolution],(Unnamed Layer* 40) [Scale],(Unnamed Layer* 41) [Activation],(Unnamed Layer* 42) [Convolution],(Unnamed Layer* 43) [Scale],(Unnamed Layer* 44) [Activation],(Unnamed Layer* 45) [Convolution],(Unnamed Layer* 46) [Scale],(Unnamed Layer* 47) [Activation],(Unnamed Layer* 48) [Convolution],(Unnamed Layer* 49) [Scale],(Unnamed Layer* 50) [Activation],(Unnamed Layer* 51) [Convolution],(Unnamed Layer* 52) [Scale],(Unnamed Layer* 53) [Activation],(Unnamed Layer* 54) [Convolution],(Unnamed Layer* 55) [Scale],(Unnamed Layer* 56) [Activation],(Unnamed Layer* 57) [Convolution],(Unnamed Layer* 58) [Scale],(Unnamed Layer* 59) [Activation],(Unnamed Layer* 60) [Convolution],(Unnamed Layer* 61) [Scale],(Unnamed Layer* 62) [Activation],(Unnamed Layer* 63) [Convolution],(Unnamed Layer* 64) [Scale],(Unnamed Layer* 65) [Activation],(Unnamed Layer* 66) [Convolution],(Unnamed Layer* 67) [Scale],(Unnamed Layer* 68) [Activation],(Unnamed Layer* 69) [Convolution],(Unnamed Layer* 70) [Scale],(Unnamed Layer* 71) [Activation],(Unnamed Layer* 72) [Convolution],(Unnamed Layer* 73) [Scale],(Unnamed Layer* 74) [Activation],(Unnamed Layer* 75) [Convolution],(Unnamed Layer* 76) [Scale],(Unnamed Layer* 77) [Activation],(Unnamed Layer* 78) [Convolution],(Unnamed Layer* 79) [Scale],(Unnamed Layer* 80) [Activation],pooling_replaced,fc_replaced},
[TensorRT] INFO: --------------- Layers running on GPU:
[TensorRT] INFO: topk_layer,
[TensorRT] INFO: Detected 1 inputs and 1 output network tensors.
python3: ../rtExt/dla/native/dlaExecuteRunner.cpp:123: virtual void nvinfer1::rt::dla::DLANativeRunner::allocateResources(const nvinfer1::rt::CommonContext&): Assertion `context.dlaContext->getDLACore() >= 0 && context.dlaContext->getDLACore() < mCore.numEngines()' failed.
Traceback (most recent call last):
  File "code/main.py", line 327, in <module>
    main()
  File "code/main.py", line 317, in main
    launch_handle_generate_engine(benchmark_name, benchmark_conf, need_gpu, need_dla)
  File "code/main.py", line 80, in launch_handle_generate_engine
    raise RuntimeError("Building engines failed!")
RuntimeError: Building engines failed!
Makefile:298: recipe for target 'generate_engines' failed
make: *** [generate_engines] Error 1
```

Did we miss something obvious?

Many thanks in advance.

**Comment by nvpohanh** [comment]
Could you try building the engines for each benchmark-scenario combination one by one? Like `make generate_engines RUN_ARGS="--benchmarks=resnet --scenarios=SingleStream --verbose"`?

If you still hit the same error, could you try `rm -rf /tmp/tensorrt-dla-build-* 2>/dev/null || true` and `echo 1 > /proc/sys/vm/drop_caches` before building the engine, just to make sure that we have a clean starting environment without any caches?

Please let me know if it works or does not work. Thanks!

**Comment by ens-lg4** [comment]
Dear @nvpohanh ,

Thank you very much - clearing the caches indeed did the trick for us, so now all the 19 engines get generated.

**Comment by nvpohanh** [comment]
@ens-lg4 Glad to hear that! would you mind if we close this issue? we can reopen if other issues show up. Thanks!

**Comment by ens-lg4** [comment]
Sure, thanks!
