### ISSUE TITLE
make build failed incase of nvidia

### ISSUE THREAD

**Issue by sandip761** [mlperf/inference_results_v0.5#28]

**Comment by nvpohanh** [comment]
Could you attach a full log for `make build_loadgen VERBOSE=1`? It looks like it's something wrong in ninja. Thanks

**Comment by sandip761** [comment]
Building loadgen...
bootstrapping ninja...
/bin/sh: 1: ./src/inline.sh: Permission denied
when running:  "./src/inline.sh" kBrowsePy < ./src/browse.py > build/browse_py.h
Traceback (most recent call last):
  File "configure.py", line 462, in <module>
    variables=[('varname', 'kBrowsePy')])
  File "configure.py", line 164, in build
    self._run_command(self._expand(cmd, local_vars))
  File "configure.py", line 189, in _run_command
    subprocess.check_call(cmdline, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '"./src/inline.sh" kBrowsePy < ./src/browse.py > build/browse_py.h' returned non-zero exit status 126
Makefile:267: recipe for target 'build_loadgen' failed
make: *** [build_loadgen] Error 1

**Comment by alawami** [comment]
I am also having an issue with building the docker container image. When running `make build_docker`.

Below is my output:

```
Building Docker image
docker build -t mlperf-inference:user-latest \
	--network host -f docker/Dockerfile .
Sending build context to Docker daemon  3.758MB
Step 1/34 : ARG BASE_IMAGE=nvcr.io/nvidia/tensorrt:19.09-py3
Step 2/34 : FROM ${BASE_IMAGE}
 ---> c350816d65e6
Step 3/34 : SHELL ["/bin/bash", "-c"]
 ---> Using cache
 ---> 8c1130e0b437
Step 4/34 : RUN echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/ /" > /etc/apt/sources.list.d/cuda.list  && apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub  && apt-get update  && apt-get install -y --no-install-recommends build-essential autoconf libtool git         curl wget pkg-config sudo ca-certificates vim-tiny automake libssl-dev         bc python3-dev python3-pip python2.7-dev google-perftools gdb libglib2.0-dev clang python-pip sshfs libre2-dev  && apt-get install -y --no-install-recommends cuda-cudart-dev-10-1 cuda-curand-dev-10-1 cuda-nvrtc-dev-10-1 cuda-command-line-tools-10-1 libcublas-dev  && ln -s cuda-10.1 /usr/local/cuda  && apt-get remove -y cmake  && apt-get remove -y libgflags-dev  && apt-get remove -y libprotobuf-dev  && apt-get -y autoremove  && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 0b7a01dc5924
Step 5/34 : ENV LC_ALL=C.UTF-8
 ---> Using cache
 ---> 5bf3788f36bc
Step 6/34 : ENV LANG=C.UTF-8
 ---> Using cache
 ---> 657a2107c7a7
Step 7/34 : RUN python2 -m pip install --upgrade pip  && python2 -m pip install --upgrade setuptools wheel virtualenv  && python2 -m pip install ez_setup==0.9  && python2 -m pip install numpy  && python2 -m pip install absl-py==0.7.1
 ---> Running in d738f03991ad
Cache entry deserialization failed, entry ignored
Collecting pip
  Downloading https://files.pythonhosted.org/packages/54/0c/d01aa759fdc501a58f431eb594a17495f15b88da142ce14b5845662c13f3/pip-20.0.2-py2.py3-none-any.whl (1.4MB)
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed pip-20.0.2
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting setuptools
  Downloading setuptools-44.1.0-py2.py3-none-any.whl (583 kB)
Collecting wheel
  Downloading wheel-0.34.2-py2.py3-none-any.whl (26 kB)
Collecting virtualenv
  Downloading virtualenv-20.0.18-py2.py3-none-any.whl (4.6 MB)
Collecting importlib-metadata<2,>=0.12; python_version < "3.8"
  Downloading importlib_metadata-1.6.0-py2.py3-none-any.whl (30 kB)
Collecting pathlib2<3,>=2.3.3; python_version < "3.4" and sys_platform != "win32"
  Downloading pathlib2-2.3.5-py2.py3-none-any.whl (18 kB)
Collecting importlib-resources<2,>=1.0; python_version < "3.7"
  Downloading importlib_resources-1.4.0-py2.py3-none-any.whl (20 kB)
Collecting filelock<4,>=3.0.0
  Downloading filelock-3.0.12.tar.gz (8.5 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-QgrMjY/filelock/setup.py'"'"'; __file__='"'"'/tmp/pip-install-QgrMjY/filelock/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-QgrMjY/filelock/pip-egg-info
         cwd: /tmp/pip-install-QgrMjY/filelock/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/bash -c python2 -m pip install --upgrade pip  && python2 -m pip install --upgrade setuptools wheel virtualenv  && python2 -m pip install ez_setup==0.9  && python2 -m pip install numpy  && python2 -m pip install absl-py==0.7.1' returned a non-zero code: 1
Makefile:134: recipe for target 'build_docker' failed
make: *** [build_docker] Error 1
```

**Comment by nvpohanh** [comment]
@alawami Your issue might be fixed by this: https://github.com/mlperf/inference_results_v0.5/pull/22/files
