### ISSUE TITLE
Intel: ImageNet accuracy logs cannot be postprocessed with accuracy-imagenet.py

### ISSUE THREAD

**Issue by psyhtest** [mlperf/inference_results_v0.5#29]
When reproducing Intel's v0.5 submission, we found that their `mlperf_log_accuracy.json` cannot be processed using the official [`accuracy_imagenet.py`](https://github.com/mlperf/inference/blob/master/v0.5/classification_and_detection/tools/accuracy-imagenet.py) tool (md5 hash: `14ebc71db7376291d2ee62094be3dd3c`):

```bash
anton@diviniti:~/projects/mlperf/inference_results_v0.5_dividiti/closed/Intel/results$ for mlperf_log_accuracy_json in \
  ./ICL-I3-1005G1_OpenVINO-Windows/resnet/Offline/accuracy/mlperf_log_accuracy.json \
  ./ICL-I3-1005G1_OpenVINO-Windows/resnet/SingleStream/accuracy/mlperf_log_accuracy.json \
  ./nnpi-1000-2x_onnx/resnet/Offline/accuracy/mlperf_log_accuracy.json \
  ./nnpi-1000-2x_onnx/resnet/Server/accuracy/mlperf_log_accuracy.json \
  ./clx-9282-2s_pytorch-caffe2/resnet/Offline/accuracy/mlperf_log_accuracy.json \
  ./clx-9282-2s_pytorch-caffe2/resnet/SingleStream/accuracy/mlperf_log_accuracy.json \
  ./clx-9282-2s_pytorch-caffe2/resnet/Server/accuracy/mlperf_log_accuracy.json \
; do \
  /usr/bin/python3.6 \
  /home/anton/CK_TOOLS/mlperf-inference-dividiti.v0.5-intel/inference/v0.5/classification_and_detection/tools/accuracy-imagenet.py \
  --mlperf-accuracy-file $mlperf_log_accuracy_json \
  --imagenet-val-file /home/anton/CK_TOOLS/dataset-imagenet-ilsvrc2012-aux/val.txt \
  --dtype float32 \
; done
accuracy=0.100%, good=50, total=50000
accuracy=0.100%, good=50, total=50000
accuracy=0.100%, good=50, total=50000
accuracy=0.100%, good=50, total=50000
accuracy=0.100%, good=50, total=50000
accuracy=0.100%, good=50, total=50000
accuracy=0.100%, good=50, total=50000
```
The result is the same even if the logs themselves are (almost all) different:
```
anton@diviniti:~/projects/mlperf/inference_results_v0.5_dividiti/closed/Intel/results$ for mlperf_log_accuracy_json in \
  ./ICL-I3-1005G1_OpenVINO-Windows/resnet/Offline/accuracy/mlperf_log_accuracy.json \
  ./ICL-I3-1005G1_OpenVINO-Windows/resnet/SingleStream/accuracy/mlperf_log_accuracy.json \
  ./nnpi-1000-2x_onnx/resnet/Offline/accuracy/mlperf_log_accuracy.json \
  ./nnpi-1000-2x_onnx/resnet/Server/accuracy/mlperf_log_accuracy.json \
  ./clx-9282-2s_pytorch-caffe2/resnet/Offline/accuracy/mlperf_log_accuracy.json \
  ./clx-9282-2s_pytorch-caffe2/resnet/SingleStream/accuracy/mlperf_log_accuracy.json \
  ./clx-9282-2s_pytorch-caffe2/resnet/Server/accuracy/mlperf_log_accuracy.json \
; do \
  md5sum $mlperf_log_accuracy_json \
; done
```

The provided `accuracy.txt` file are also not (all) identical:
```
anton@diviniti:~/projects/mlperf/inference_results_v0.5_dividiti/closed/Intel/results$ for accuracy_txt in \
  ./ICL-I3-1005G1_OpenVINO-Windows/resnet/Offline/accuracy/accuracy.txt \
  ./ICL-I3-1005G1_OpenVINO-Windows/resnet/SingleStream/accuracy/accuracy.txt \
  ./nnpi-1000-2x_onnx/resnet/Offline/accuracy/accuracy.txt \
  ./nnpi-1000-2x_onnx/resnet/Server/accuracy/accuracy.txt \
  ./clx-9282-2s_pytorch-caffe2/resnet/Offline/accuracy/accuracy.txt \
  ./clx-9282-2s_pytorch-caffe2/resnet/SingleStream/accuracy/accuracy.txt \
  ./clx-9282-2s_pytorch-caffe2/resnet/Server/accuracy/accuracy.txt \
; do \
  cat $accuracy_txt \
; done
accuracy=76.400%, good=38200, total=50000
accuracy=76.234%, good=38117, total=50000
accuracy=75.720%, good=37860, total=50000
accuracy=75.720%, good=37860, total=50000
accuracy=75.766%, good=37883, total=50000
accuracy=76.124%, good=38062, total=50000
accuracy=76.124%, good=38062, total=50000
```

**Comment by psyhtest** [comment]
Same for [Tencent's results](https://github.com/mlperf/inference_results_v0.5/tree/master/closed/Tencent/results):
```
anton@velociti:/data/anton/inference_results_v0.5/closed/Tencent/results$ for mlperf_log_accuracy_json in \
  ./clx-8255c-4s_pytorch-caffe2/mobilenet/singlestream/accuracy/mlperf_log_accuracy.json \
  ./clx-8255c-4s_pytorch-caffe2/mobilenet/server/accuracy/mlperf_log_accuracy.json \
  ./clx-8255c-4s_pytorch-caffe2/mobilenet/offline/accuracy/mlperf_log_accuracy.json \
  ./clx-8255c-4s_pytorch-caffe2/resnet50/singlestream/accuracy/mlperf_log_accuracy.json \
  ./clx-8255c-4s_pytorch-caffe2/resnet50/server/accuracy/mlperf_log_accuracy.json \
  ./clx-8255c-4s_pytorch-caffe2/resnet50/offline/accuracy/mlperf_log_accuracy.json \
; do \
  /usr/bin/python3.6 \
  /home/anton/CK_TOOLS/mlperf-inference-dividiti.v0.5-intel/inference/v0.5/classification_and_detection/tools/accuracy-imagenet.py \
  --mlperf-accuracy-file $mlperf_log_accuracy_json \
  --imagenet-val-file /home/anton/CK_TOOLS/dataset-imagenet-ilsvrc2012-aux/val.txt \
  --dtype float32 \
; done
accuracy=0.100%, good=50, total=50000
accuracy=0.100%, good=50, total=50000
accuracy=0.100%, good=50, total=50000
accuracy=0.100%, good=50, total=50000
accuracy=0.100%, good=50, total=50000
accuracy=0.100%, good=50, total=50000

anton@velociti:/data/anton/inference_results_v0.5/closed/Tencent/results$ for mlperf_log_accuracy_json in \
  ./clx-8255c-4s_pytorch-caffe2/mobilenet/singlestream/accuracy/mlperf_log_accuracy.json \
  ./clx-8255c-4s_pytorch-caffe2/mobilenet/server/accuracy/mlperf_log_accuracy.json \
  ./clx-8255c-4s_pytorch-caffe2/mobilenet/offline/accuracy/mlperf_log_accuracy.json \
  ./clx-8255c-4s_pytorch-caffe2/resnet50/singlestream/accuracy/mlperf_log_accuracy.json \
  ./clx-8255c-4s_pytorch-caffe2/resnet50/server/accuracy/mlperf_log_accuracy.json \
  ./clx-8255c-4s_pytorch-caffe2/resnet50/offline/accuracy/mlperf_log_accuracy.json \
; do \
  md5sum $mlperf_log_accuracy_json \
; done
d9af76294c84714c81a9cdad3cdb0ba4  ./clx-8255c-4s_pytorch-caffe2/mobilenet/singlestream/accuracy/mlperf_log_accuracy.json
c1a9950c7ade21ab2469a58ca77e1983  ./clx-8255c-4s_pytorch-caffe2/mobilenet/server/accuracy/mlperf_log_accuracy.json
92236382f183ace223510f7b44e4ae3a  ./clx-8255c-4s_pytorch-caffe2/mobilenet/offline/accuracy/mlperf_log_accuracy.json
a0685a8c3021c1f6bebe9d9527d2919b  ./clx-8255c-4s_pytorch-caffe2/resnet50/singlestream/accuracy/mlperf_log_accuracy.json
dc3048d6e61e80d4188e9c689645c175  ./clx-8255c-4s_pytorch-caffe2/resnet50/server/accuracy/mlperf_log_accuracy.json
15fe627fee1b1ff4bfec6cd2a217c4c0  ./clx-8255c-4s_pytorch-caffe2/resnet50/offline/accuracy/mlperf_log_accuracy.json

anton@velociti:/data/anton/inference_results_v0.5/closed/Tencent/results$ for accuracy_txt in \
  ./clx-8255c-4s_pytorch-caffe2/mobilenet/singlestream/accuracy/accuracy.txt \
  ./clx-8255c-4s_pytorch-caffe2/mobilenet/server/accuracy/accuracy.txt \
  ./clx-8255c-4s_pytorch-caffe2/mobilenet/offline/accuracy/accuracy.txt \
  ./clx-8255c-4s_pytorch-caffe2/resnet50/singlestream/accuracy/accuracy.txt \
  ./clx-8255c-4s_pytorch-caffe2/resnet50/server/accuracy/accuracy.txt \
  ./clx-8255c-4s_pytorch-caffe2/resnet50/offline/accuracy/accuracy.txt \
; do \
  cat $accuracy_txt \
; done
accuracy=70.394%, good=35197, total=50000
accuracy=70.408%, good=35204, total=50000
accuracy=70.392%, good=35196, total=50000
accuracy=76.124%, good=38062, total=50000
accuracy=76.124%, good=38062, total=50000
accuracy=75.710%, good=37855, total=50000
```

**Comment by psyhtest** [comment]
OK, `--dtype int32` should be used:
```
anton@velociti:/data/anton/inference_results_v0.5/closed/Tencent/results$ for mlperf_log_accuracy_json in \
  ./clx-8255c-4s_pytorch-caffe2/mobilenet/singlestream/accuracy/mlperf_log_accuracy.json \
  ./clx-8255c-4s_pytorch-caffe2/mobilenet/server/accuracy/mlperf_log_accuracy.json \
  ./clx-8255c-4s_pytorch-caffe2/mobilenet/offline/accuracy/mlperf_log_accuracy.json \
  ./clx-8255c-4s_pytorch-caffe2/resnet50/singlestream/accuracy/mlperf_log_accuracy.json \
  ./clx-8255c-4s_pytorch-caffe2/resnet50/server/accuracy/mlperf_log_accuracy.json \
  ./clx-8255c-4s_pytorch-caffe2/resnet50/offline/accuracy/mlperf_log_accuracy.json \
; do \
  /usr/bin/python3.6 \
  /home/anton/CK_TOOLS/mlperf-inference-dividiti.v0.5-intel/inference/v0.5/classification_and_detection/tools/accuracy-imagenet.py \
  --mlperf-accuracy-file $mlperf_log_accuracy_json \
  --imagenet-val-file /home/anton/CK_TOOLS/dataset-imagenet-ilsvrc2012-aux/val.txt \
  --dtype int32 \
; done
accuracy=70.394%, good=35197, total=50000
accuracy=70.420%, good=35210, total=50000
accuracy=70.392%, good=35196, total=50000
accuracy=76.124%, good=38062, total=50000
accuracy=76.124%, good=38062, total=50000
accuracy=75.710%, good=37855, total=50000
```
but not `--dtype int64`:
```
anton@velociti:/data/anton/inference_results_v0.5/closed/Tencent/results$ for mlperf_log_accuracy_json in \
  ./clx-8255c-4s_pytorch-caffe2/mobilenet/singlestream/accuracy/mlperf_log_accuracy.json \
  ./clx-8255c-4s_pytorch-caffe2/mobilenet/server/accuracy/mlperf_log_accuracy.json \
  ./clx-8255c-4s_pytorch-caffe2/mobilenet/offline/accuracy/mlperf_log_accuracy.json \
  ./clx-8255c-4s_pytorch-caffe2/resnet50/singlestream/accuracy/mlperf_log_accuracy.json \
  ./clx-8255c-4s_pytorch-caffe2/resnet50/server/accuracy/mlperf_log_accuracy.json \
  ./clx-8255c-4s_pytorch-caffe2/resnet50/offline/accuracy/mlperf_log_accuracy.json \
; do \
  /usr/bin/python3.6 \
  /home/anton/CK_TOOLS/mlperf-inference-dividiti.v0.5-intel/inference/v0.5/classification_and_detection/tools/accuracy-imagenet.py \
  --mlperf-accuracy-file $mlperf_log_accuracy_json \
  --imagenet-val-file /home/anton/CK_TOOLS/dataset-imagenet-ilsvrc2012-aux/val.txt \
  --dtype int64 \
; done
accuracy=36.514%, good=18257, total=50000
accuracy=70.420%, good=35210, total=50000
accuracy=70.392%, good=35196, total=50000
accuracy=76.124%, good=38062, total=50000
accuracy=76.124%, good=38062, total=50000
accuracy=75.710%, good=37855, total=50000
```

**Comment by psyhtest** [comment]
Similarly, `--dtype int32` should be used for the Intel results:
```
anton@velociti:/data/anton/inference_results_v0.5/closed/Intel/results$ for mlperf_log_accuracy_json in \
  ./ICL-I3-1005G1_OpenVINO-Windows/resnet/Offline/accuracy/mlperf_log_accuracy.json \
  ./ICL-I3-1005G1_OpenVINO-Windows/resnet/SingleStream/accuracy/mlperf_log_accuracy.json \
  ./nnpi-1000-2x_onnx/resnet/Offline/accuracy/mlperf_log_accuracy.json \
  ./nnpi-1000-2x_onnx/resnet/Server/accuracy/mlperf_log_accuracy.json \
  ./clx-9282-2s_pytorch-caffe2/resnet/Offline/accuracy/mlperf_log_accuracy.json \
  ./clx-9282-2s_pytorch-caffe2/resnet/SingleStream/accuracy/mlperf_log_accuracy.json \
  ./clx-9282-2s_pytorch-caffe2/resnet/Server/accuracy/mlperf_log_accuracy.json \
; do \
  /usr/bin/python3.6 \
  /home/anton/CK_TOOLS/mlperf-inference-dividiti.v0.5-intel/inference/v0.5/classification_and_detection/tools/accuracy-imagenet.py \
  --mlperf-accuracy-file $mlperf_log_accuracy_json \
  --imagenet-val-file /home/anton/CK_TOOLS/dataset-imagenet-ilsvrc2012-aux/val.txt \
  --dtype int32 \
; done
accuracy=76.400%, good=38200, total=50000
accuracy=76.234%, good=38117, total=50000
accuracy=75.720%, good=37860, total=50000
accuracy=75.720%, good=37860, total=50000
accuracy=75.766%, good=37883, total=50000
accuracy=76.124%, good=38062, total=50000
accuracy=76.124%, good=38062, total=50000
```

`--dtype=int64` can only be used for the PyTorch/Caffe2 result:
```
anton@velociti:/data/anton/inference_results_v0.5/closed/Intel/results$ for mlperf_log_accuracy_json in \
  ./ICL-I3-1005G1_OpenVINO-Windows/resnet/Offline/accuracy/mlperf_log_accuracy.json \
  ./ICL-I3-1005G1_OpenVINO-Windows/resnet/SingleStream/accuracy/mlperf_log_accuracy.json \
  ./nnpi-1000-2x_onnx/resnet/Offline/accuracy/mlperf_log_accuracy.json \
  ./nnpi-1000-2x_onnx/resnet/Server/accuracy/mlperf_log_accuracy.json \
  ./clx-9282-2s_pytorch-caffe2/resnet/Offline/accuracy/mlperf_log_accuracy.json \
  ./clx-9282-2s_pytorch-caffe2/resnet/SingleStream/accuracy/mlperf_log_accuracy.json \
  ./clx-9282-2s_pytorch-caffe2/resnet/Server/accuracy/mlperf_log_accuracy.json \
; do \
  /usr/bin/python3.6 \
  /home/anton/CK_TOOLS/mlperf-inference-dividiti.v0.5-intel/inference/v0.5/classification_and_detection/tools/accuracy-imagenet.py \
  --mlperf-accuracy-file $mlperf_log_accuracy_json \
  --imagenet-val-file /home/anton/CK_TOOLS/dataset-imagenet-ilsvrc2012-aux/val.txt \
  --dtype int64 \
; done
Traceback (most recent call last):
  File "/home/anton/CK_TOOLS/mlperf-inference-dividiti.v0.5-intel/inference/v0.5/classification_and_detection/tools/accuracy-imagenet.py", line 74, in <module>
    main()
  File "/home/anton/CK_TOOLS/mlperf-inference-dividiti.v0.5-intel/inference/v0.5/classification_and_detection/tools/accuracy-imagenet.py", line 60, in main
    data = np.frombuffer(bytes.fromhex(j['data']), dtype_map[args.dtype])
ValueError: buffer size must be a multiple of element size
Traceback (most recent call last):
  File "/home/anton/CK_TOOLS/mlperf-inference-dividiti.v0.5-intel/inference/v0.5/classification_and_detection/tools/accuracy-imagenet.py", line 74, in <module>
    main()
  File "/home/anton/CK_TOOLS/mlperf-inference-dividiti.v0.5-intel/inference/v0.5/classification_and_detection/tools/accuracy-imagenet.py", line 60, in main
    data = np.frombuffer(bytes.fromhex(j['data']), dtype_map[args.dtype])
ValueError: buffer size must be a multiple of element size
Traceback (most recent call last):
  File "/home/anton/CK_TOOLS/mlperf-inference-dividiti.v0.5-intel/inference/v0.5/classification_and_detection/tools/accuracy-imagenet.py", line 74, in <module>
    main()
  File "/home/anton/CK_TOOLS/mlperf-inference-dividiti.v0.5-intel/inference/v0.5/classification_and_detection/tools/accuracy-imagenet.py", line 60, in main
    data = np.frombuffer(bytes.fromhex(j['data']), dtype_map[args.dtype])
ValueError: buffer size must be a multiple of element size
Traceback (most recent call last):
  File "/home/anton/CK_TOOLS/mlperf-inference-dividiti.v0.5-intel/inference/v0.5/classification_and_detection/tools/accuracy-imagenet.py", line 74, in <module>
    main()
  File "/home/anton/CK_TOOLS/mlperf-inference-dividiti.v0.5-intel/inference/v0.5/classification_and_detection/tools/accuracy-imagenet.py", line 60, in main
    data = np.frombuffer(bytes.fromhex(j['data']), dtype_map[args.dtype])
ValueError: buffer size must be a multiple of element size
accuracy=75.766%, good=37883, total=50000
accuracy=76.124%, good=38062, total=50000
accuracy=76.124%, good=38062, total=50000
```
