### ISSUE TITLE
Failed to create Engine for SSD-Mobilenet on DLA core

### ISSUE THREAD

**Issue by sandip761** [mlperf/inference_results_v0.5#34]
python3: ../rtExt/dla/native/dlaExecuteRunner.cpp:123: virtual void nvinfer1::rt::dla::DLANativeRunner::allocateResources(const nvinfer1::rt::CommonContext&): Assertion `context.dlaContext->getDLACore() >= 0 && context.dlaContext->getDLACore() < mCore.numEngines()' failed.
Traceback (most recent call last):
  File "code/main.py", line 328, in <module>
    main()
  File "code/main.py", line 318, in main
    launch_handle_generate_engine(benchmark_name, benchmark_conf, need_gpu, need_dla)
  File "code/main.py", line 80, in launch_handle_generate_engine
    raise RuntimeError("Building engines failed!")
RuntimeError: Building engines failed!
Makefile:298: recipe for target 'generate_engines' failed
make: *** [generate_engines] Error 1

**Comment by nvpohanh** [comment]
@sandip761 Could you try the suggested solution here: https://github.com/mlperf/inference_results_v0.5/issues/23#issuecomment-597358583 ? Let me know if that doesn't work. Thanks

**Comment by sandip761** [comment]
I am able to create engine dla core , while running for performance i got this errror.

[04/25/2020-16:40:39] [E] [TRT] ../rtExt/dla/native/dlaExecuteRunner.cpp (71) - DLA Error in execute: 7 (Input tensor register failed.)
[04/25/2020-16:40:39] [E] [TRT] FAILED_EXECUTION: std::exception
NVMEDIA_DLA : 1599, ERROR: registerTensorBuffer failed
[04/25/2020-16:40:39] [E] [TRT] ../rtExt/dla/native/dlaExecuteRunner.cpp (71) - DLA Error in execute: 7 (Input tensor register failed.)
[04/25/2020-16:40:39] [E] [TRT] FAILED_EXECUTION: std::exception
NVMEDIA_DLA : 1599, ERROR: registerTensorBuffer failed
[04/25/2020-16:40:39] [E] [TRT] ../rtExt/dla/native/dlaExecuteRunner.cpp (71) - DLA Error in execute: 7 (Input tensor register failed.)
[04/25/2020-16:40:39] [E] [TRT] FAILED_EXECUTION: std::exception
NVMEDIA_DLA : 1599, ERROR: registerTensorBuffer failed
[04/25/2020-16:40:39] [E] [TRT] ../rtExt/dla/native/dlaExecuteRunner.cpp (71) - DLA Error in execute: 7 (Input tensor register failed.)
[04/25/2020-16:40:39] [E] [TRT] FAILED_EXECUTION: std::exception
NVMEDIA_DLA : 1599, ERROR: registerTensorBuffer failed
[04/25/2020-16:40:39] [E] [TRT] ../rtExt/dla/native/dlaExecuteRunner.cpp (71) - DLA Error in execute: 7 (Input tensor register failed.)
[04/25/2020-16:40:39] [E] [TRT] FAILED_EXECUTION: std::exception
[04/25/2020-16:40:39] [I] Average over 10 runs is 0.393837 ms (host walltime is 0.453828 ms, 99% percentile time is 0.395264).
trtexec: ../rtExt/dla/nvmItem.cpp:22: nvinfer1::rt::dla::NvmItem::~NvmItem(): Assertion `!mCudaMemory || !mNvmTensor' failed.
Aborted (core dumped)

**Comment by nvpohanh** [comment]
@sandip761 You built the DLA engine with BS=8 but ran it with BS=4. DLA does not support dynamic batch size.
