### ISSUE TITLE
Pytorch issue

### ISSUE THREAD

**Issue by sandip761** [mlperf/inference_results_v0.5#35]
Even if Pytorch installed in xavier, why I am getting this issue:

[2020-05-26 11:56:30,976 main.py:292 INFO] Using config files: measurements/Xavier/ssd-large/SingleStream/config.json
[2020-05-26 11:56:30,977 __init__.py:142 INFO] Parsing config file measurements/Xavier/ssd-large/SingleStream/config.json ...
[2020-05-26 11:56:30,978 main.py:296 INFO] Processing config "Xavier_ssd-large_SingleStream"
[2020-05-26 11:56:31,132 main.py:83 INFO] Building engines for ssd-large benchmark in SingleStream scenario...
[2020-05-26 11:56:31,136 main.py:100 INFO] Building GPU engine for Xavier_ssd-large_SingleStream
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/blaize-xavier/mmcard/inference_results_v0.5/closed/NVIDIA/code/main.py", line 101, in handle_generate_engine
    b = get_benchmark(benchmark_name, config)
  File "/home/blaize-xavier/mmcard/inference_results_v0.5/closed/NVIDIA/code/main.py", line 42, in get_benchmark
    SSDResNet34 = import_module("code.ssd-large.tensorrt.SSDResNet34").SSDResNet34
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/blaize-xavier/mmcard/inference_results_v0.5/closed/NVIDIA/code/ssd-large/tensorrt/SSDResNet34.py", line 37, in <module>
    load_torch_weights = import_module("code.ssd-large.tensorrt.utils").load_torch_weights
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/blaize-xavier/mmcard/inference_results_v0.5/closed/NVIDIA/code/ssd-large/tensorrt/utils.py", line 19, in <module>
    import torch
  File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 97, in <module>
    from torch._C import *
ImportError: libtorch.so.1: cannot open shared object file: No such file or directory
[2020-05-26 11:56:31,833 main.py:83 INFO] Building engines for ssd-large benchmark in SingleStream scenario...
[2020-05-26 11:56:31,836 main.py:100 INFO] Building GPU engine for Xavier_ssd-large_SingleStream
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/blaize-xavier/mmcard/inference_results_v0.5/closed/NVIDIA/code/main.py", line 101, in handle_generate_engine
    b = get_benchmark(benchmark_name, config)
  File "/home/blaize-xavier/mmcard/inference_results_v0.5/closed/NVIDIA/code/main.py", line 42, in get_benchmark
    SSDResNet34 = import_module("code.ssd-large.tensorrt.SSDResNet34").SSDResNet34
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/blaize-xavier/mmcard/inference_results_v0.5/closed/NVIDIA/code/ssd-large/tensorrt/SSDResNet34.py", line 37, in <module>
    load_torch_weights = import_module("code.ssd-large.tensorrt.utils").load_torch_weights
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/blaize-xavier/mmcard/inference_results_v0.5/closed/NVIDIA/code/ssd-large/tensorrt/utils.py", line 19, in <module>
    import torch
  File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 97, in <module>
    from torch._C import *
ImportError: libtorch.so.1: cannot open shared object file: No such file or directory
[2020-05-26 11:56:32,519 main.py:83 INFO] Building engines for ssd-large benchmark in SingleStream scenario...
[2020-05-26 11:56:32,522 main.py:100 INFO] Building GPU engine for Xavier_ssd-large_SingleStream
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/blaize-xavier/mmcard/inference_results_v0.5/closed/NVIDIA/code/main.py", line 101, in handle_generate_engine
    b = get_benchmark(benchmark_name, config)
  File "/home/blaize-xavier/mmcard/inference_results_v0.5/closed/NVIDIA/code/main.py", line 42, in get_benchmark
    SSDResNet34 = import_module("code.ssd-large.tensorrt.SSDResNet34").SSDResNet34
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/blaize-xavier/mmcard/inference_results_v0.5/closed/NVIDIA/code/ssd-large/tensorrt/SSDResNet34.py", line 37, in <module>
    load_torch_weights = import_module("code.ssd-large.tensorrt.utils").load_torch_weights
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/blaize-xavier/mmcard/inference_results_v0.5/closed/NVIDIA/code/ssd-large/tensorrt/utils.py", line 19, in <module>
    import torch
  File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 97, in <module>
    from torch._C import *
ImportError: libtorch.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "code/main.py", line 328, in <module>
    main()
  File "code/main.py", line 318, in main
    launch_handle_generate_engine(benchmark_name, benchmark_conf, need_gpu, need_dla)
  File "code/main.py", line 80, in launch_handle_generate_engine
    raise RuntimeError("Building engines failed!")
RuntimeError: Building engines failed!
Makefile:298: recipe for target 'generate_engines' failed
make: *** [generate_engines] Error 1

**Comment by nvpohanh** [comment]
How did you install pytorch? Did you use this script? https://github.com/mlperf/inference_results_v0.5/blob/master/closed/NVIDIA/scripts/install_xavier_dependencies.sh

Also, what is LD_LIBRARY_PATH in your case?

**Comment by sandip761** [comment]
I use the script to install the pytorch. According to bashrc ,export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64:$LD_LIBRARY_PATH

**Comment by nvpohanh** [comment]
For me, the path to libtorch.so is at `/usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so`.

**Comment by sandip761** [comment]
I manually uninstall and install it , now it is working fine. Thanks for your response.

**Comment by nvpohanh** [comment]
@sandip761 Could you close this issue? Thanks
